// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNRLNNNwfKDxfwJ3-vtdywvBDRe1bgXSw',
    appId: '1:895803487361:web:7ab7f304a9b574e04fc980',
    messagingSenderId: '895803487361',
    projectId: 'fola-app',
    authDomain: 'fola-app.firebaseapp.com',
    storageBucket: 'fola-app.firebasestorage.app',
    measurementId: 'G-0RK7B13P0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHF5H-d1vH68GSfC6th47ZqQcEiFUojU0',
    appId: '1:895803487361:android:99ecc1abfa67444e4fc980',
    messagingSenderId: '895803487361',
    projectId: 'fola-app',
    storageBucket: 'fola-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJavVKhzER_qQBZb-cYhIuVlNOSbAtan8',
    appId: '1:895803487361:ios:f9f78065bf79237f4fc980',
    messagingSenderId: '895803487361',
    projectId: 'fola-app',
    storageBucket: 'fola-app.firebasestorage.app',
    iosBundleId: 'com.example.folaApp',
  );
}
